### ISSUE TITLE
Update events not sync properly - cursor click  / update form event ..

### ISSUE THREAD

**Issue by eladh** [mozilla/togetherjs#1044]
Hello everyone :-)

we start integrate TogetherJS  in our AngularJS application.
As part of our Pilot we got some issue , we will appreciate your help/ideas ,10x .
1. triggering form-update working only in the first time and for the first char/key 
   in the second update (or next key press event) i got error with the field history not defined
2. its seems like when clicking on drop-box / buttons widgets (using Twitter bootstrap) 
    the cursor click event echo back to the master browser and close the widget.
    is there any way to create configuration of Master and Viewer only. so one of the browsers
    will just receive events (cursor , click , form update..) and will process them locally but will not  
    send any update to the Master browser.
3. when clicking on modal widgets (like popup calendar) its seems that the cursor is display in the background and upon clicking there isn't any cursor update event .

thanks again,
Elad Hirsch.

**Comment by roccomuso** [comment]
+1

**Comment by eladh** [comment]
@roccomuso

see www.sessionstack.com
