### ISSUE TITLE
Use TogetherJS to collaboratively edit content on GitHub

### ISSUE THREAD

**Issue by mitar** [mozilla/togetherjs#1058]
We wanted to use TogetherJS in our team to work together on GitHub content, but it seems only site admins can add it to their sites, you cannot just enable TogetherJS on a third-party site? Is there a browser extension or way to do this?

**Comment by woniesong92** [comment]
It may be possible to do it on your own website using Github API: https://developer.github.com/v3/
Set up a website, enable togetherjs to edit a form together, and submit that form via Github API request.
