### ISSUE TITLE
WebSocket connection to hub.togetherjs.com closes with code 1006 every few seconds

### ISSUE THREAD

**Issue by hellifiknow** [mozilla/togetherjs#1063]
The message in the browser console is "WebSocket close" "unclean" "code:" 1006 "reason:" "none". And is happening every 5 to 10 seconds. Each time the connection closes a new init-connection is received, but is not consistently reporting the number of peers. 

You can reproduce this by opening the drawing application example https://togetherjs.com/examples/drawing/ and observe the console in dev tools.

This seemed to start in the last couple of days. My guess is that the server hub.togethers.com may be in a weird state since the client code hasn't changed in a while.

**Comment by simonwex** [comment]
I agree that it seems to be server code or the ELB doing this. ELB timeout is set at 900 seconds, though.

**Comment by woniesong92** [comment]
Will post an update here ASAP. Thank you for reporting!!

**Comment by jbuck** [comment]
@woniesong92 I'm not seeing this right now in Firefox 37 or Chrome 42. Which browser are you using?

**Comment by jbuck** [comment]
Err, sorry, meant to say @hellifiknow

**Comment by simonwex** [comment]
@jbuck I was able to repro in latest chrome, firefox yesterday. The load endpoint confirmed that it was dumping connections every few seconds. I killed the service last night, it'd been running untouched for over a year. I didn't think it solved the problem, but I am unable to reproduce the problem today. It could have been an issue with the AWS ELB.

@hellifiknow could you re-open if you're still seeting it?
