### ISSUE TITLE
use TogetherJS completely on my own server?

### ISSUE THREAD

**Issue by Niklas-Peter** [mozilla/togetherjs#1074]
You offer the node.js hub server, but how can I host the .js and .css files completely on my own server?
The baseUrl seems to be hard coded in togetherjs.js. I could change it, but what is about all the other files, can I download them anywhere?

**Comment by woniesong92** [comment]
Since all the source is public, you can clone this repository and edit it the way you want, and compile it to get your version of `togetherjs.js` file. Please refer to the readme file.
