### ISSUE TITLE
Can't use togetherjs

### ISSUE THREAD

**Issue by xrsrke** [mozilla/togetherjs#1123]
I downloaded the source code to the server but it does not work. I do not know where I did wrong. Looking forward for your help

demo http://raynext.com/togetherjs-develop/site/examples/drawing/index.html

![image](https://user-images.githubusercontent.com/22252984/28243732-d4b9d3e6-69ff-11e7-8ef4-670aab4c7a8e.png)

**Comment by Martin080793** [comment]
The Bootstrap CSS File is missing. You also need to include jquery and all the neccessary JavaScript files.





[Example.zip](https://github.com/mozilla/togetherjs/files/1182240/Example.zip)

**Comment by woniesong92** [comment]
Thanks @Martin080793
