### ISSUE TITLE
Is Together.js being maintained?

### ISSUE THREAD

**Issue by Coder1400** [mozilla/togetherjs#1138]
Thanks to everyone working on this. Together.js is awesome. 

However, Many issues are open, latest commit was a while back, and seems like the codebase uses deprecated libraries. Can this be used in production?

**Comment by gagarine** [comment]
Ok. The answer seem to be no. See also http://www.ianbicking.org/blog/2014/09/professional-transitions.html

Are they any good fork?

**Comment by gagarine** [comment]
see #1127

**Comment by oskarkrawczyk** [comment]
JSFiddle team is now maintaining the project
