### ISSUE TITLE
Plans for browser add-on?

### ISSUE THREAD

**Issue by rugk** [mozilla/togetherjs#1148]
Are there already plans for a browser add-on, so this can/could be used on any website by some users?

I would really appreciate it…

**Comment by rugk** [comment]
Ah, I found:
* https://addons.mozilla.org/de/firefox/addon/browse-together/
* https://addons.mozilla.org/de/firefox/addon/togetherjs-companion/

So they actually seem to be already there.

**Comment by joeyguerra** [comment]
You should close this issue then.
