### ISSUE TITLE
Using Static Copy of Client Causes Conflicts

### ISSUE THREAD

**Issue by migregorio** [mozilla/togetherjs#1166]
When I build a static copy of the client and include the files on my website, there appear to be conflicts with other libraries on my website (e.g., after I click the togetherjs button to start a session, I encounter the error "uncaught typeerror $(...).selectric is not a function" when I try to make selections in my selectric dropdowns but works fine until _after_ I start the togetherjs session).

I don't encounter any conflicts/errors like that when I reference https://togetherjs.com/togetherjs-min.js instead of the local, static copy. Does anyone know the cause of this?

**Comment by chriswilber** [comment]
Did you ever resolve this?
