### ISSUE TITLE
hub.togetherjs stopped working correctly

### ISSUE THREAD

**Issue by oskarkrawczyk** [mozilla/togetherjs#1171]
Hi guys, I'm aware TogetherJS is not actively maintained, but it seems like something has broken recently.

We're using TogetherJS in JSFiddle and when try to initiate a connection we're now always getting: 

```
[Info] Connecting to – "https://hub.togetherjs.com/hub/xwVn3K8Ooo" – "https://jsfiddle.net/odr8g7vh/#" (session.js, line 104)
[Error] WebSocket connection to 'wss://hub.togetherjs.com/hub/xwVn3K8Ooo' failed: Unexpected response code: 503
[Error] WebSocket error: – undefined
	(anonymous function) (channels.js:193)
[Error] WebSocket close – "unclean" – "code:" – 1006 – "reason:" – "none"
	(anonymous function) (channels.js:174)
```

Any chance anyone knows what might have happened and if it's possible to fix?

**Comment by OpenHypervideo** [comment]
We're having the same issues. Are the servers permanently down? Like, has Mozilla stopped hosting the project or is this a temporary problem?

**Comment by oskarkrawczyk** [comment]
@OpenHypervideo Most down forever. Since it was unmaintained, if the server (Heroku here) went down, no one is around to fix it.

**Comment by OpenHypervideo** [comment]
That's really unfortunate. Especially as the exact code running https://hub.togetherjs.com/ has not been made public, right? That would at least make it easier to deploy an alternative somewhere..

**Comment by oskarkrawczyk** [comment]
We'll be trying to get the hub server working under @jsfiddle - https://github.com/mozilla/togetherjs/issues/1127
