### ISSUE TITLE
Server issues

### ISSUE THREAD

**Issue by zqdevelopment** [mozilla/togetherjs#1173]
Hi, we are from ZeroQode and we have a plugin created to integrate "TogetherJS" in Bubble.is and not long ago our page started getting a server error that seems to be coming from the "TogetherJS" library. We will be very grateful if you could assist us with troubleshooting this problem. I'm attaching a console screenshot with the problem. It appears that the hub server is down.
![console](https://user-images.githubusercontent.com/28785569/77932089-b89a7a00-72b5-11ea-950f-0de23297bca9.PNG).

Thank you

**Comment by joeyguerra** [comment]
Hey @zqdevelopment . You should check out issue #1172 

The hub server is no longer available so you'll probably have to setup a new one and configure together.js to use that one instead.
