### ISSUE TITLE
WebSocket connection to failed

### ISSUE THREAD

**Issue by Parveen-Mothsara** [mozilla/togetherjs#1207]
Hi Team,

We are getting below error 
Firefox can’t establish a connection to the server at wss://hub.togetherjs.com/hub/TabmBGBSJy.

**Comment by daveidivide** [comment]
Same issue here

**Comment by Parveen-Mothsara** [comment]
> Same issue here

Hi @daveidivide ,
                      Create your own hub server,because hub.togetherjs.com is down

**Comment by nandhi10** [comment]
Were you able to create your own server ? i see deprecated "github:miksago/node-websocket-server#master". how can i work around this ?

**Comment by Parveen-Mothsara** [comment]
> Were you able to create your own server ? i see deprecated "github:miksago/node-websocket-server#master". how can i work around this ?

Hi @nandhi10  i am using windows server, and no issue occurred.
