### ISSUE TITLE
add setting to have towtruck create invite URLs with ?towtruck=... (no #)

### ISSUE THREAD

**Issue by ianb** [mozilla/togetherjs#217]
This relates to this Wordpress-plugin bug: https://github.com/DerekMarcinyshyn/towtruck/issues/1

I'd propose `TowTruckConfig.inviteQueryString=true`.  Once implemented the plugin should set this.

**Comment by woniesong92** [comment]
Not a high priority. Closing this for now and please reopen it later if this is critical.
