### ISSUE TITLE
Participant states

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#368]
I want to add more detail to the participant states.  It can be confusing as to what each participant is doing.

1. For an active participant on the same page as you - Their avatar in the dock will have an opacity of 1.  Their cursor + name opacity will be 1.

2. For an idle participant on the same page as you - Their avatar in the dock will have an opacity of 0.3, and it will have a small icon/badge on the lower right over their avatar that signifies they're idle.  In addition, their cursor will have an opacity of 0.3 as will their name.

3. For a participant on another page - Their avatar will have an opacity of 0.3 in the dock, and there will be a badge/icon on top of their avatar that signifies they're on another page.  In addition, they will not have a cursor on the page.

![Screen Shot 2013-04-11 at 11 08 03 AM](https://f.cloud.github.com/assets/2692810/369228/c4ef8a4e-a2d2-11e2-859d-981461088d20.png)

**Comment by woniesong92** [comment]
Not a high priority. Closing this for now and please reopen it later if this is critical.
