### ISSUE TITLE
User can highlight an area on the page

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#49]
A user can select the highlighter tool and draw a rectangle with it. When in highlight mode, all click events should be swallowed . 

Here's a good example of the drawing mode:

https://vimeo.com/7064475#t=0m37s

All users should be able to see the same result. A click on the highlight should see it animate away. (A faster version of this) http://docs.jquery.com/UI/Effects/Puff

**Comment by woniesong92** [comment]
Not a high priority. Closing it for now.
