### ISSUE TITLE
TinyMCE support

### ISSUE THREAD

**Issue by ianb** [mozilla/togetherjs#723]
Supporting TinyMCE would be good, it's used on several CMS's.

What we'd need to figure out is:

* How to detect the editor is on the page, and where it is attached to (we don't want to assume there is only one editor)
* Probably access to some "editor" instance associated with the element
* A way to listen for changes
* A way to get and set the text

That's assuming that syncing the HTML underlying the WYSIWYG editor will be sufficient.  I'm not 100% sure that's the case, but it's worth trying.

**Comment by woniesong92** [comment]
Merged.
