### ISSUE TITLE
Start button modification stuff is hacky and prone to not work

### ISSUE THREAD

**Issue by ianb** [mozilla/togetherjs#788]
While it's fine how the dock comes out of the start button, trying to change the class and text is less reliable, and never works on the client that joins.

The other option is to make those changes globally, not rely on the notion of a "start" button.  That would also probably work, and would be reliable in the face of more conditions.

**Comment by Ryuno-Ki** [comment]
According to the documentation I would first [check for data-end-togetherjs-html](https://togetherjs.com/docs/#start-togetherjs-button) before hard coding the text value.
jQuery has a [data method](https://api.jquery.com/data/#data-html5) to get and set the data attribute.

(I am aware of TogetherJS being discontinued.)

**Comment by lkraav** [comment]
togetherjs discontinued? wow, that's the worst news if true, unless it's getting replaced by smth better. i can't find references to this news on google, @Ryuno-Ki any pointers please?

**Comment by Ryuno-Ki** [comment]
Read @ianb's [blogpost](http://www.ianbicking.org/blog/2014/09/professional-transitions.html). At least it Mozilla Labs, which incubates this projects is about to shut down. So it may continue as community project.

Hopefully Ian is informing users if Mozilla intends to shut down the servers …
