### ISSUE TITLE
Fix IE

### ISSUE THREAD

**Issue by ianb** [mozilla/togetherjs#812]
IE 10 (without webrtc) is possible to support, but needs lots of fixing up.  

IE 11 will potentially have webrtc, but getting IE 10 working first is better.

IE 9 would require xhr polling or other techniques, and I'm not sure we want to pursue that.

**Comment by woniesong92** [comment]
I am closing all IE-related issues because they are not priority. Reopen them later if they are necessary.

**Comment by yuhong** [comment]
I already have a pull request to fix the problem.

**Comment by woniesong92** [comment]
@yuhong I reopened the issue. Thanks for your PR! I am going through all the issues right now and will try to leave only the "important" ones open to maintain the project.

**Comment by yuhong** [comment]
And someone already tested it, as you can see in the comments, and the code is broken anyway.

**Comment by woniesong92** [comment]
https://github.com/mozilla/togetherjs/pull/1029
