### ISSUE TITLE
Interop issue on IE 10 & 11

### ISSUE THREAD

**Issue by reybango** [mozilla/togetherjs#867]
TogetherJS doesn't appear to work in IE10 or IE11. This may be due to lack of testing and we saw a browser-sniff in there specifically for MSIE.

Would be great to have the team test in these browsers to ensure interop. Free VMs to test these browser versions can be found here:

http://www.modern.ie/en-us/virtualization-tools

**Comment by woniesong92** [comment]
I am closing all IE-related issues because they are not priority. Reopen them later if they are necessary.
