### ISSUE TITLE
select random color from a more limited pallette

### ISSUE THREAD

**Issue by aarondruck** [mozilla/togetherjs#93]
let's make the cursors a magenta hue, maybe model etherpad's colors for participants.  resembles redlines in print.

![Screen Shot 2013-03-04 at 10 07 52 AM](https://f.cloud.github.com/assets/2692810/217936/17337838-84fb-11e2-98c2-db87fe222e34.png)

**Comment by woniesong92** [comment]
Not a high priority. Closing this for now and please reopen it later if this is critical.
