### ISSUE TITLE
sync contenteditable HTML5 attribut

### ISSUE THREAD

**Issue by istiti** [mozilla/togetherjs#946]
I know that textfields are syncronized but is it possible to syncronise all contenteditable  attributs of html tag? if it's possible it wil be very nice:)

**Comment by cedkim** [comment]
If you have 1 `contenteditable`, you could always sync it with a `textarea` using the `input` event like this:
```html
<div id="contentEditor" oninput="document.getElementById('contentTextarea').value=this.innerHTML;" contenteditable></div>
<textarea id="contentTextarea" oninput="document.getElementById('contentEditor').innerHTML=this.value;" hidden="hidden"></textarea>
```
